# Generated by Django 4.1.1 on 2022-09-11 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_alter_room_options_room_participants"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message", options={"ordering": ["-updated", "-created"]},
        ),
    ]
